# Generated by Django 5.2.5 on 2025-08-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='image_path',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
